name: llm-qa-chat
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohttp=3.8.5=py311h459d7ec_0
  prefix: /opt/conda/envs/llm-qa-chat
